DATASET: places205
NUM_DEVICES: 8
LOGGER_FREQUENCY: 10
MODEL:
  NUM_CLASSES: 205
  DEPTH: 50
  MODEL_NAME: resnet_supervised_finetune_linear
  MEMONGER: True
  EXTRACT_FEATURES_ONLY: True
  EXTRACT_BLOBS: [
    res_conv1_bn_resize,
    res2_2_branch2c_bn_s8k16_resize,
    res3_3_branch2c_bn_s5k13_resize,
    res4_5_branch2c_bn_s3k8_resize,
    res5_2_branch2c_bn_s1k6_resize]
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 256
  SCALE: 256
  CROP_SIZE: 224
  GLOBAL_RESIZE_VALUE: 224
  DATA_TRANSFORMS: [scale, global_resize]
  DATA_PROCESSING: [color_normalization]
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 256
  CROP_SIZE: 224
