DATASET: voc2007
NUM_DEVICES: 4
LOGGER_FREQUENCY: 10
MODEL:
  TEST_MODEL: True
  DEPTH: 50
  NUM_CLASSES: 20
  MODEL_NAME: resnet_supervised_finetune_full
  BN_MOMENTUM: 0.9
  BN_EPSILON: 1.0000001e-5
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  FINE_TUNE: True
  BN_NO_SCALE_SHIFT: True
  NO_BIAS_DECAY: True
  FORCE_BN_TEST_MODE: False
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 128
  EVALUATION_FREQUENCY: 40
  SCALE: 256
  CROP_SIZE: 224
  DATA_TRANSFORMS: [random_sized_crop, horizontal_flip]
  DATA_PROCESSING: [color_normalization, lighting]
  # IN1K RN50 supervised
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/resnet50_in1k_supervised.pkl
  # Places205 supervised
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/resnet50_places205_supervised.pkl
TEST:
  # for VOC2007, we train on the trainval split and evaluate on the test set.
  DATA_TYPE: test
  BATCH_SIZE: 128
  CROP_SIZE: 224
SOLVER:
  BASE_LR: 0.01 # used for IN1K supervised
  # BASE_LR: 0.15 # used for places205 supervised
  STEP_SIZES: [1600]
  NUM_ITERATIONS: 3000
  WEIGHT_DECAY: 0.000001
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  GAMMA: 0.1
  NESTEROV: True
CHECKPOINT:
  DIR: .
  CHECKPOINT_PERIOD: 40
METRICS:
  TYPE: AP
