DATASET: coco
NUM_DEVICES: 8
LOGGER_FREQUENCY: 10
MODEL:
  NUM_CLASSES: 80
  MODEL_NAME: resnet_supervised_finetune_linear
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  DEPTH: 50
  EXTRACT_FEATURES_ONLY: True
  EXTRACT_BLOBS: [
    res_conv1_bn_resize,
    res2_2_branch2c_bn_s8k16_resize,
    res3_3_branch2c_bn_s5k13_resize,
    res4_5_branch2c_bn_s3k8_resize,
    res5_2_branch2c_bn_s1k6_resize]
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 256
  SCALE: 256
  CROP_SIZE: 224
  GLOBAL_RESIZE_VALUE: 224
  DATA_TRANSFORMS: [scale, global_resize]
  DATA_PROCESSING: [color_normalization]
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 256
  CROP_SIZE: 224
  # ResNet50 IN1K supervised
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/resnet50_in1k_supervised.pkl
