DATASET: places205
NUM_DEVICES: 8
LOGGER_FREQUENCY: 10
LOSS_BLOBS: [loss_c1, loss_c2, loss_c3, loss_c4, loss_c5, loss_pool1, loss_pool2, loss_pool5]
ACCURACY_BLOBS: [pred_c1, pred_c2, pred_c3, pred_c4, pred_c5, pred_pool1, pred_pool2, pred_pool5]
MODEL:
  NUM_CLASSES: 205
  MODEL_NAME: alexnet_jigsaw_finetune_linear
  BN_MOMENTUM: 0.999
  BN_EPSILON: 1.0000001e-5
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  BN_NO_SCALE_SHIFT: True
  FINE_TUNE: True
  NO_BIAS_DECAY: False
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 256
  EVALUATION_FREQUENCY: 5000
  CROP_SIZE: 227
  DATA_TRANSFORMS: [scale, center_crop, horizontal_flip]
  DATA_PROCESSING: [color_normalization, lighting]
  # AlexNet Jigsaw IN1K pretext - best
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/alexnet_jigsaw_in1k_pretext.pkl
  # AlexNet Jigsaw IN22K pretext - best
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/alexnet_jigsaw_in22k_pretext.pkl
  # AlexNet Jigsaw YFCC100M pretext - best
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/alexnet_jigsaw_yfcc100m_pretext.pkl
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 256
  CROP_SIZE: 227
SOLVER:
  BASE_LR: 0.01
  STEP_SIZES: [40000, 40000, 40000]
  NUM_ITERATIONS: 140000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  GAMMA: 0.1
  NESTEROV: False
CHECKPOINT:
  DIR: .
  CHECKPOINT_PERIOD: 5000
METRICS:
  TYPE: topk
