DATASET: voc2007
NUM_DEVICES: 8
LOGGER_FREQUENCY: 10
COLORIZATION:
  COLOR_ON: True
MODEL:
  NUM_CLASSES: 20
  DEPTH: 50
  MODEL_NAME: resnet_colorize_finetune_linear
  ALLOW_INPLACE_SUM: True
  MEMONGER: True
  EXTRACT_FEATURES_ONLY: True
  EXTRACT_BLOBS: [
    res_conv1_bn_resize,
    res2_2_branch2c_bn_s8k16_resize,
    res3_3_branch2c_bn_s5k13_resize,
    res4_5_branch2c_bn_s3k8_resize,
    res5_2_branch2c_bn_s2k12_resize
  ]
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 256
  SCALE: 256
  CROP_SIZE: 224
  GLOBAL_RESIZE_VALUE: 224
  DATA_TRANSFORMS: [scale, global_resize]
  DATA_PROCESSING: []
TEST:
  # for VOC2007, we train on the trainval split and evaluate on the test set.
  DATA_TYPE: test
  BATCH_SIZE: 256
  CROP_SIZE: 224
  # 48 init
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/resnet50_colorization_lowShot_in22k_pretext.pkl
  # ResNet50 Colorization YFCC100M pretext - best
  PARAMS_FILE: https://dl.fbaipublicfiles.com/fair_self_supervision_benchmark/models/resnet50_colorization_yfcc100m_pretext.pkl
