DATASET: voc2007
NUM_DEVICES: 8
LOGGER_FREQUENCY: 10
MODEL:
  NUM_CLASSES: 20
  MODEL_NAME: caffenet_bvlc_supervised_finetune_linear
  EXTRACT_FEATURES_ONLY: True
  EXTRACT_BLOBS: [
    conv1_s4k19_resize,
    conv2_s3k12_resize,
    conv3_s1k9_resize,
    conv4_s1k9_resize,
    conv5_s1k8_resize]
TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 256
  CROP_SIZE: 227
  GLOBAL_RESIZE_VALUE: 227
  DATA_TRANSFORMS: [scale, global_resize]
  DATA_PROCESSING: [mean_normalization]
TEST:
  # for VOC2007, we train on the trainval split and evaluate on the test set.
  DATA_TYPE: test
  BATCH_SIZE: 256
  CROP_SIZE: 227
